version: '3'
services:
  hello:
    image: ECR_URL/hello
    logging:
      driver: awslogs
      options: 
        awslogs-group: hello
        awslogs-region: eu-west-1
        awslogs-stream-prefix: /ecs/
